class HealthTips {
  static List<String> tips = [
    'Stay hydrated by drinking plenty of water.',
    'Include fruits and vegetables in your daily diet.',
    'Engage in regular physical activity like walking or light exercises.',
    'Get enough sleep to support overall health.',
    'Stay socially active and maintain a strong support network.',
    'Limit processed and sugary foods in your diet.',
    'Monitor your blood pressure regularly.',
    'Practice good hygiene to prevent infections.',
    'Maintain a healthy weight for your body.',
    'Avoid smoking and limit alcohol consumption.',
    'Visit your doctor for regular check-ups.',
    'Manage stress through relaxation techniques.',
    'Protect your skin from the sun with sunscreen.',
    'Practice good dental hygiene with regular check-ups.',
    'Do balance exercises to prevent falls.',
    'Stay mentally active with puzzles and games.',
    'Limit salt intake for heart health.',
    'Eat a variety of nutrient-rich foods.',
    'Maintain a positive attitude towards life.',
    'Engage in activities you enjoy for mental well-being.',
    'Practice portion control to manage weight.',
    'Get regular eye check-ups for vision health.',
    'Limit caffeine intake for better sleep.',
    'Consider taking vitamin D supplements for bone health.',
    'Include fiber-rich foods in your diet.',
    'Practice deep breathing exercises for relaxation.',
    'Avoid sitting for long periods; take breaks to move.',
    'Participate in community events and socialize.',
    'Stay up-to-date on vaccinations for flu and other diseases.',
    'Keep medications organized and take them as prescribed.',
    'Wear comfortable and supportive shoes.',
    'Practice mindfulness meditation for stress reduction.',
    'Engage in hobbies to stay mentally stimulated.',
    'Limit screen time for better sleep quality.',
    'Maintain a routine for better sleep patterns.',
    'Stay informed about health-related news.',
    'Learn and practice proper handwashing techniques.',
    'Use proper lifting techniques to avoid injuries.',
    'Practice good posture to prevent back pain.',
    'Learn and practice stress management techniques.',
    'Attend health and wellness classes in your community.',
    'Stay connected with friends and family.',
    'Consider low-impact exercises like swimming.',
    'Use assistive devices if needed for mobility.',
    'Practice good foot care, especially for diabetics.',
    'Keep emergency contact information handy.',
    'Stay informed about mental health resources.',
    'Express your feelings and communicate openly.',
    'Enjoy the outdoors for fresh air and sunshine.',
  ];
}
